# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-01 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='amount',
            new_name='paid_amount',
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_channel',
            field=models.CharField(choices=[('cod', 'cod'), ('upi', 'upi'), ('paytm', 'paytm'), ('ebs', 'ebs'), ('paypal', 'paypal'), ('card', 'card'), ('net_banking', 'net_banking'), ('wallet', 'wallet'), ('other', 'other')], default='cod', max_length=30),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('created', 'created'), ('success', 'success'), ('failed', 'failed')], default='created', max_length=30),
        ),
    ]
