# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-20 06:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import ecommerce.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('brand_name', models.CharField(max_length=100, null=True)),
                ('brand_desc', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BrandMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('typ', models.CharField(choices=[('thumb', 'thumb'), ('image', 'image'), ('video', 'video'), ('banner', 'banner')], default='image', max_length=15)),
                ('attachment', models.FileField(null=True, upload_to=ecommerce.models.brandMediaPath)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category_name', models.CharField(max_length=100, null=True)),
                ('category_desc', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('typ', models.CharField(choices=[('thumb', 'thumb'), ('image', 'image'), ('video', 'video'), ('banner', 'banner')], default='image', max_length=15)),
                ('attachment', models.FileField(null=True, upload_to=ecommerce.models.categoryMediaPath)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('product_name', models.CharField(max_length=100)),
                ('product_sku', models.CharField(max_length=100)),
                ('product_price', models.FloatField(default=None, null=True)),
                ('product_weight', models.FloatField(default=None, null=True)),
                ('product_desc', models.CharField(max_length=1000, null=True)),
                ('product_short_desc', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductAtrribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('attribute_name', models.CharField(max_length=100, null=True)),
                ('attribute_value', models.CharField(max_length=100, null=True)),
                ('attribute_unit', models.CharField(choices=[('cm', 'cm'), ('metre', 'metre'), ('inch', 'inch'), ('gram', 'gram'), ('kilogram', 'kilogram'), ('ton', 'ton')], default='metre', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ProductMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('typ', models.CharField(choices=[('thumb', 'thumb'), ('image', 'image'), ('video', 'video'), ('banner', 'banner')], default='image', max_length=15)),
                ('attachment', models.FileField(null=True, upload_to=ecommerce.models.productMediaPath)),
            ],
        ),
        migrations.CreateModel(
            name='ProductMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('taxCode', models.CharField(blank=True, max_length=100)),
                ('taxRate', models.FloatField(blank=True, default=None, null=True)),
                ('typ', models.CharField(choices=[('SSN', 'SSN'), ('HSN', 'HSN')], default='HSN', max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_attribute',
            field=models.ManyToManyField(blank=True, related_name='prod_attr', to='ecommerce.ProductAtrribute'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prod_brand', to='ecommerce.Brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod_cat', to='ecommerce.Category'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_media',
            field=models.ManyToManyField(blank=True, related_name='prod_media', to='ecommerce.ProductMedia'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_meta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prod_meta', to='ecommerce.ProductMeta'),
        ),
        migrations.AddField(
            model_name='category',
            name='category_media',
            field=models.ManyToManyField(blank=True, related_name='cat_media', to='ecommerce.CategoryMedia'),
        ),
        migrations.AddField(
            model_name='category',
            name='category_parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='ecommerce.Category'),
        ),
        migrations.AddField(
            model_name='brand',
            name='brand_media',
            field=models.ManyToManyField(blank=True, related_name='brand_media', to='ecommerce.BrandMedia'),
        ),
    ]
