# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-20 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_auto_20190120_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_disc_perc',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='productatrribute',
            name='attribute_unit',
            field=models.CharField(choices=[('cm', 'cm'), ('metre', 'metre'), ('inch', 'inch'), ('gram', 'gram'), ('kilogram', 'kilogram'), ('ton', 'ton'), ('none', 'none')], default='none', max_length=15),
        ),
    ]
