# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-27 09:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce', '0003_auto_20190120_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('code_name', models.CharField(max_length=100)),
                ('min_order_amount', models.PositiveIntegerField()),
                ('valid_from', models.DateTimeField()),
                ('valid_till', models.DateTimeField()),
                ('valid_count', models.PositiveIntegerField()),
                ('discount_perc', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('paid_amount', models.FloatField(default=0.0)),
                ('payment_typ', models.CharField(choices=[('cod', 'cod'), ('card', 'card'), ('upi', 'upi'), ('paypal', 'paypal'), ('paytm', 'paytm')], default='cod', max_length=10)),
                ('payment_status', models.CharField(choices=[('created', 'created'), ('failed', 'failed'), ('completed', 'completed')], default='created', max_length=10)),
                ('total_amount', models.FloatField()),
                ('order_tracking_id', models.CharField(max_length=100)),
                ('discount_perc', models.FloatField(default=0.0)),
                ('additional_notes', models.CharField(max_length=500, null=True)),
                ('order_cancellable', models.BooleanField(default=True)),
                ('order_cancelled', models.BooleanField(default=False)),
                ('coupon_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_coupon', to='order_management.CouponCode')),
            ],
        ),
        migrations.CreateModel(
            name='OrderedProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('product_quantity', models.PositiveIntegerField()),
                ('paid_amount', models.FloatField(default=0.0)),
                ('product_amount', models.FloatField()),
                ('status', models.CharField(choices=[('created', 'created'), ('packed', 'packed'), ('shipped', 'shipped'), ('inTransit', 'inTransit'), ('reachedNearestHub', 'reachedNearestHub'), ('outForDelivery', 'outForDelivery'), ('delivered', 'delivered'), ('cancelled', 'cancelled'), ('returned', 'returned')], default='created', max_length=30)),
                ('cancellable', models.BooleanField(default=True)),
                ('cancelled', models.BooleanField(default=False)),
                ('additional_notes', models.CharField(max_length=500, null=True)),
                ('discount_perc', models.FloatField(default=0.0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_product', to='ecommerce.Product')),
            ],
        ),
        migrations.CreateModel(
            name='TrackingLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('logTxt', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='orderedproduct',
            name='tracking_log',
            field=models.ManyToManyField(blank=True, related_name='trackLogs', to='order_management.TrackingLog'),
        ),
        migrations.AddField(
            model_name='order',
            name='ordered_products',
            field=models.ManyToManyField(related_name='order_products', to='order_management.OrderedProduct'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
