# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-27 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0002_couponcode_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount_paid_by_wallet',
            field=models.FloatField(null=True),
        ),
    ]
