# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-01 16:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0007_order_payment_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='amount_paid_by_wallet',
        ),
        migrations.RemoveField(
            model_name='order',
            name='paid_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_typ',
        ),
    ]
